import Head from 'next/head';

import Footer from '@/Components-candl/Footer';
import Menu from '@/components/Menu';
import Banner from '@/Components-candl/Banner';
import About from '@/Components-candl/About';

import Photos from '@/Components-candl/Photos';
import Explain from '@/Components-candl/Explain';
import Others from '@/Components-candl/Others';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <Menu />

                <Banner />
                <div style={()}>
                <About />
                <Explain />
                </div>

                <Photos />
                <div className="body"><Others />
                  <Footer /></div>

            </main>
        </>
    );
}
