import Head from 'next/head';

import Footer from '@/components/Footer';
import Menu from '@/components/Menu';
import Banner from '@/Components-goldibite/Banner';
import About from '@/Components-goldibite/About';

import Photos from '@/Components-goldibite/Photos';
import Explain from '@/Components-goldibite/Explain';
import Others from '@/Components-goldibite/Others';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <Menu />

                <Banner />
                <About />
                <Explain />
             

                <Photos />
                <Others />
                <Footer />

            </main>
        </>
    );
}
