import Head from 'next/head';

import Footer from '@/components/Footer';
import BlockOne from '@/components/BlockOne';
import BlockTwo from '@/components/BlockTwo';
import BlockThree from '@/components/BlockThree';
import Banner from '@/components/Banner';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Projects</h1>
        <BlockOne />
        <BlockTwo />
        <BlockThree />
        <Banner />
        <Footer />
      </main> {/* Close the main tag properly */}
    </>
  );
}
