"use client"
import { useState, useEffect } from 'react';
import Head from 'next/head';

import Footer from '@/components/Footer';
import BlockOne from '@/components/BlockOne';
import BlockTwo from '@/components/BlockTwo';
import BlockThree from '@/components/BlockThree';
import BlockFour from '@/components/BlockFour';
import Menu from '@/components/Menu';

import Banner from '@/components/Banner';

export default function Home() {
  const [cursorPosition, setCursorPosition] = useState({ x: 0, y: 0 });

  useEffect(() => {
    const handleMouseMove = (e) => {
      setCursorPosition({ x: e.clientX, y: e.clientY });
    };

    window.addEventListener("mousemove", handleMouseMove);
    return () => {
      window.removeEventListener("mousemove", handleMouseMove);
    };
  }, []);

  return (
    <div className="home-page">
      {/* Custom Cursor */}
      <div 
        style={{
          position: 'fixed',
          top: `${cursorPosition.y}px`,
          left: `${cursorPosition.x}px`,
          width: '50px',
          height: '50px',
          backgroundColor: 'red',
          borderRadius: '50%',
          zIndex: 1000,
          pointerEvents: 'none',
          transform: 'translate(-50%, -50%)', // Centers cursor
        }}
      ></div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Menu />
        <Banner />
    
        <BlockOne />
        <BlockTwo />
        <BlockThree />
        
        <Footer />
      </main>
    </div>
  );
}
