import Head from 'next/head';

import Footer from '@/components/Footer';
import BlockOne from '@/components/BlockOne';
import BlockTwo from '@/components/BlockTwo';
import BlockThree from '@/components/BlockThree';
import Banner from '@/components/Banner';
import Menu from '@/components/Menu';
import About from '@/components/About';
import Video from '@/components/Video';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <Menu />
        <Video />
        <BlockOne />
        <BlockTwo />
        <BlockThree />
        
       
        <Footer />
      </main>
    </>
  );
}
