import Head from 'next/head';

import Footer from '@/components/Footer';
import BlockOne from '@/components/BlockOne';
import BlockTwo from '@/components/BlockTwo';
import BlockThree from '@/components/BlockThree';

import Menu from '@/components/Menu';
import About from '@/components/About';
import Video from '@/components/Video';
import Reviews from '@/components/Reviews';
import Banner from '@/components/Banner';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <Menu />
        <Banner />
        <div class="animation-demo">
          <button class="animation-button">
            <span class="animation-confetti">👌</span>
            <span class="animation-confetti">🎍</span>
            <span class="animation-confetti">😍</span>
          </button>

        </div>
       
        <Video />
        <BlockOne />
        <BlockTwo />
        <BlockThree />
        
       
        <Footer />
      </main>
    </>
  );
}
