import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/Footer'
import Link from 'next/link'
import Parallex

import HomeProjects from '@/components/Home-projects'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <HomeProjects/>
      </main>
      <footer>
      <Footer/>
      </footer>
    </>
  )
}
