import Head from 'next/head';

import Footer from '@/components/Footer';

import Parallex from '@/components/Parallax'; // Ensure correct spelling if it's 'Parallax'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <Parallex />
        <Footer />
      </main> {/* Close the main tag properly */}
    </>
  );
}
