"use client"
import { useState, useEffect } from 'react';
import Head from 'next/head';

import Footer from '@/components/Footer';
import BlockOne from '@/components/BlockOne';
import BlockTwo from '@/components/BlockTwo';
import BlockThree from '@/components/BlockThree';

import Menu from '@/components/Menu';

import Video from '@/components/Video';

import Banner from '@/components/Banner';
export default function Home() {
 const[cursorPostion, setCursorPostion] = useState({x: 0, y: 0});
  useEffect(() => {
  
  }, []);
  const handleCustomCursor = (e) => {
    
    setCursorPostion({x: e.pageX, y: e.pageY});
  };
  return (
    <div className='home-page' onMouseMove={handleCustomCursor}>
<div cl>

</div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Menu />
        <Banner />


        <Video />
        <BlockOne />
        <BlockTwo />
        <BlockThree />


        <Footer />

      </main>
    </div>
  );
}
