import Head from 'next/head';

import Footer from '@/components/Footer';
import StickyBlockOne from '@/components/BlockOne';
import Stick


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <StickyBlockOne />
            <StickyBlockTwo />
            <StickyBlockThree />
        <Footer />
      </main> {/* Close the main tag properly */}
    </>
  );
}
