import Head from 'next/head';
import styles from '@/styles/Home.module.css'; // Make sure these styles are being used or remove this line if not
import Footer from '@/components/Footer';
import Link from 'next/link'; // This import is unused, consider removing if not needed later
import Parallex from '@/components/Parallax'; // Ensure correct spelling if it's 'Parallax'

import HomeProjects from '@/components/HomeProjects'; // Ensure directory and file naming is correct

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeProjects />
        <Parallex />
        <Footer />
      </main> {/* Close the main tag properly */}
    </>
  );
}
