import Head from 'next/head';

import Footer from '@/';
import Menu from '@/components/Menu';
import Banner from '@/Components-paw/Banner';
import About from '@/Components-paw/About';


import Photos from '@/Components-paw/Photos';
import Explain from '@/Components-paw/Explain';
import Others from '@/Components-paw/Others';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            
                <Menu />
                <Banner />
                <About />
                <Explain />
                <Photos />
                        
                <div className="body"><Others />
                <Footer /></div>
        
        </>
    );
}
