import Head from 'next/head';

import Footer from '@';
import Menu from '@/components/Menu';
import Banner from '@/Components-questify/Banner';
import About from '@/Components-questify/About';

import Photos from '@/Components-questify/Photos';


import Others from "@/Components-questify/Others"


export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <Menu />

                <Banner />
                <About />
           
              
             

                <Photos />
                        
                <div className="body"><Others />
                <Footer /></div>
            </main>
        </>
    );
}
