import Head from 'next/head';

import Footer from '@/components/Footer';
import Menu from '@/components/Menu';
import Banner from '@/Components-wellness/Banner';
import About from '@/Components-wellness/About';
import Logo from '@/Components-wellness/Logo';
import Photos from '@/Components-wellness/Photos';
import Explain from '@/Components-wellness/Explain';
import Mp3 from "@/Components-wellness/Mp3";
import Others from "@/Components-wellness/Others"

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <Menu />

                <Banner />
                <About />
                <Explain />
              
             

                <Photos />
                <Others />
                <Footer />

            </main>
        </>
    );
}
